In [1]:
import numpy

In [2]:
a=numpy.array([10,20,30,40])
print(a)

[10 20 30 40]


In [3]:
type(a)

numpy.ndarray

In [4]:
list1=[10,20,30,40]
print(list1)
print(type(list1))

[10, 20, 30, 40]
<class 'list'>


In [5]:
a1=numpy.array(list1)
print(a1)
print(type(a1))

[10 20 30 40]
<class 'numpy.ndarray'>


In [10]:
import numpy as np
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
x=[10,20,30,40]
a=np.asarray(x)
print(a)
print(type(a))

[10 20 30 40]
<class 'numpy.ndarray'>


In [14]:
#Restructuring a Numpy array

#Converting a linear array of 8 elements into 2 elements

arr=np.zeros(8)
print(arr)

a1=arr.reshape((2,2,2))

print(a1)

[0. 0. 0. 0. 0. 0. 0. 0.]
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [16]:
a1=np.zeros((2,3))
print(a1)

[[0. 0. 0.]
 [0. 0. 0.]]


In [18]:
a1=np.arange(2,10)
print(a1)

[2 3 4 5 6 7 8 9]


In [22]:
a1=np.arange(1,30,5)
print(a1)

[ 1  6 11 16 21 26]


In [27]:
print(a1[0])
print(a1[0:5])
print(a1[-4:-1])
print(a1[2::])
print(a1[:4])

1
[ 1  6 11 16 21]
[11 16 21]
[11 16 21 26]
[ 1  6 11 16]


In [29]:
arr_sli=slice(1,9,3)
print(arr_sli)
arr[arr_sli]

slice(1, 9, 3)


array([0., 0., 0.])

In [37]:
arr=np.loadtxt('Sample.txt',dtype=int)
print(arr)

[[1 2 3 4]
 [3 4 5 6]]
